name = "dufc-api"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "a0689f8484ba33ce434c65657ecc1092"

[[d1_databases]]
binding = "DB"
database_name = "dufc-db"
database_id = "cffa592a-5a19-4ce9-9d51-0a6690127f6a"

[vars]
APP_VERSION = "v2.0.0"
AUTH_PEPPER = "dufc-auth-pepper-v1"

# wrangler secret put MIGRATE_SECRET

[triggers]
crons = ["0 3 * * *"]
